### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine: test

**Comment by GuillaumeGomez** [comment]
@ironman-machine

**Comment by GuillaumeGomez** [comment]
@ironman-machine

**Comment by GuillaumeGomez** [comment]
@ironman-machine

**Comment by GuillaumeGomez** [comment]
@ironman-machine: status

**Comment by GuillaumeGomez** [comment]
@ironman-machine: status

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine: status

**Comment by michael-zapata** [comment]
@ironman-machine r-

**Comment by michael-zapata** [comment]
@ironman-machine r=me

**Comment by michael-zapata** [comment]
@ironman-machine p=rollup

**Comment by GuillaumeGomez** [comment]
@ironman-machine p=rollup

**Comment by GuillaumeGomez** [comment]
@ironman-machine p=rollup

**Comment by GuillaumeGomez** [comment]
@ironman-machine p=rollup

**Comment by GuillaumeGomez** [comment]
@ironman-machine p=rollup

**Comment by GuillaumeGomez** [comment]
@ironman-machine p=rollup

**Comment by GuillaumeGomez** [comment]
@ironman-machine p=rollup

**Comment by GuillaumeGomez** [comment]
@ironman-machine p=100

**Comment by GuillaumeGomez** [comment]
@ironman-machine p=100

**Comment by GuillaumeGomez** [comment]
@ironman-machine p=100

**Comment by GuillaumeGomez** [comment]
@ironman-machine: p=78 r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine: after=https://github.com/scalitytest/S3/pull/ r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine: after=https://github.com/scalitytest/S3/2

**Comment by GuillaumeGomez** [comment]
@ironman-machine: after=https://b.com/scalitytest/S3/pull/2 r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+
after=https://github.com/scalitytest/S3/pull/2

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+
after=https://github.com/scalitytest/S3/pull/2

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+
after=https://github.com/scalitytest/S3/pull/2

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+
after=https://github.com/scalitytest/S3/pull/2

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+
after=https://github.com/scalitytest/S3/pull/2

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+
after=https://github.com/scalitytest/S3/pull/2

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+
after=https://github.com/scalitytest/S3/pull/2

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+
after=https://github.com/scalitytest/S3/pull/2

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+
after=https://github.com/scalitytest/S3/pull/2

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+
after=https://github.com/scalitytest/S3/pull/2

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+
after=https://github.com/scalitytest/S3/pull/2

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+
after=https://github.com/scalitytest/S3/pull/2

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+
after=https://github.com/scalitytest/S3/pull/2

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r- after=

**Comment by GuillaumeGomez** [comment]
@ironman-machine: p=12 after=https://github.com/rust-lang/rust/pull/36320

**Comment by GuillaumeGomez** [comment]
@ironman-machine: p=12 after=https://github.com/scalitytest/S3/pull/1

**Comment by GuillaumeGomez** [comment]
@ironman-machine: p=12 after=#1

**Comment by GuillaumeGomez** [comment]
@ironman-machine: p=12 after=https://github.com/scalitytest/S3/pull/1

**Comment by GuillaumeGomez** [comment]
@ironman-machine: TEST=lol after=[https://github.com/rust-lang/rust/pull/36320,https://github.com/rust-lang/rust/pull/36320]

**Comment by GuillaumeGomez** [comment]
@ironman-machine: TEST=lol after=[rust-lang/rust#36320,https://github.com/rust-lang/rust/pull/36320]

**Comment by GuillaumeGomez** [comment]
@ironman-machine: TEST=lol after=[rust-lang/rust#36320,rust-lang/rust#36320]

**Comment by GuillaumeGomez** [comment]
@ironman-machine: TEST2=lol after=[https://github.com/rust-lang/rust/pull/36320,https://github.com/rust-lang/rust/pull/36320]

**Comment by GuillaumeGomez** [comment]
@ironman-machine: TEST2=lol after=[https://github.com/rust-lang/rust/pull/36320,https://github.com/rust-lang/rust/pull/36320]

**Comment by GuillaumeGomez** [comment]
@ironman-machine: TEST2=lol after=[rust-lang/rust#36320,https://github.com/rust-lang/rust/pull/36320]

**Comment by GuillaumeGomez** [comment]
@ironman-machine: TEST2=lol after=[rust-lang/rust#36320,rust-lang/rust#36320]

**Comment by GuillaumeGomez** [comment]
@ironman-machine: TEST2=lol after=[rust-lang/rust#36320, rust-lang/rust#36320] test3=hohoho

**Comment by GuillaumeGomez** [comment]
@ironman-machine: p=t trololo=haha huhu=hihi tester=me or=you and=them

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+ try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+ try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: try

**Comment by GuillaumeGomez** [comment]
@ironman-machine: after= r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine: after= r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine: r+

**Pull request merged**
