### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
@ironman-machine after=https://github.com/scality/Integration/issues/394 r+ clean

**Comment by GuillaumeGomez** [comment]
@ironman-machine after=scality/Integration#394 r+ clean

**Comment by GuillaumeGomez** [comment]
@ironman-machine after=scality/Integration#394 r+ clean

**Comment by GuillaumeGomez** [comment]
@ironman-machine r-

**Comment by GuillaumeGomez** [comment]
@ironman-machine clean_env

**Comment by GuillaumeGomez** [comment]
@ironman-machine clean

**Comment by GuillaumeGomez** [comment]
@ironman-machine clean

**Comment by GuillaumeGomez** [comment]
@ironman-machine clean

**Comment by GuillaumeGomez** [comment]
@ironman-machine clean

**Comment by GuillaumeGomez** [comment]
@ironman-machine clean

**Comment by GuillaumeGomez** [comment]
@ironman-machine after=https://github.com/scality/Ultron/pull/35

**Comment by GuillaumeGomez** [comment]
@ironman-machine after=scality/Ultron#35

**Comment by GuillaumeGomez** [comment]
@ironman-machine r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine r+
@ironman-machine r-

**Comment by GuillaumeGomez** [comment]
@ironman-machine r+
@ironman-machine r-

**Comment by GuillaumeGomez** [comment]
@ironman-machine r+
@ironman-machine r-

**Comment by DavidPineauScality** [comment]
@ironman-machine try

**Comment by DavidPineauScality** [comment]
Wouhou, The reverse branch mapping worked \o/

**Comment by DavidPineauScality** [comment]
@ironman-machine 
SCALITY_TOOLING_BRANCH=DavidPineauScality-patch-1
try

**Comment by DavidPineauScality** [comment]
@ironman-machine
SCALITY_TOOLING_BRANCH=
try

**Comment by GuillaumeGomez** [comment]
@ironman-machine r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine r- r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine r+

**Pull request merged**
