### PR TITLE
Update circle.yml

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
@ironman-machine SCALITY_S3_BRANCH= r- r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine SCALITY_S3_BRANCH= r- r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine SCALITY_S3_BRANCH=a @ironman-machine SCALITY_S3_BRANCH=

**Comment by GuillaumeGomez** [comment]
@ironman-machine REPO_NAME=test SCALITY_S3_BRANCH=foufou
@ironman-machine SCALITY_S3_BRANCH=

**Comment by GuillaumeGomez** [comment]
@ironman-machine SCALITY_S3_BRANCH=test

**Comment by GuillaumeGomez** [comment]
@ironman-machine SCALITY_S3_BRANCH= r- r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine t

**Comment by GuillaumeGomez** [comment]
@ironman-machine r-

**Comment by GuillaumeGomez** [comment]
@ironman-machine t

**Comment by GuillaumeGomez** [comment]
@ironman-machine t

**Comment by GuillaumeGomez** [comment]
@ironman-machine r+ after=#33

**Comment by DavidPineauScality** [comment]
@ironman-machine r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine after=#33

**Comment by GuillaumeGomez** [comment]
@ironman-machine after=#33

**Pull request closed without merging**
