### PR TITLE
nomap target testing

### PR DESCRIPTION
**Pull request by DavidPineauScality**

### CODE REVIEW

**Comment by DavidPineauScality** [comment]
@ironman-machine try

**Comment by GuillaumeGomez** [comment]
@ironman-machine r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine r- r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine r- r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine r- r+

**Comment by GuillaumeGomez** [comment]
@ironman-machine r- r+

**Pull request merged**
